### PR TITLE
Support switching mesh radio on multi-radio devices

### PR DESCRIPTION
**Pull request by aanon4**

### CODE REVIEW

**Review by ab7pa — CHANGES_REQUESTED** [review]
See comment about missing "=" in the test on line 173.  Once that is added, the feature works as designed.  Thanks very much, @aanon4

**Comment by ab7pa** [comment]
Also, for some reason the new Mesh RF link is not showing up on the **Neighbor Status** page

**Comment by aanon4** [comment]
@ab7pa Nice catch, thanks. Fix it.

**Comment by aanon4** [comment]
@ab7pa Thanks - looks like there are a few more places I need to review for where the default mesh radio is hard coded. I'll keep this in draft until I'm done with that.

**Comment by ab7pa** [comment]
BTW did I mention that this is an AWESOME FEATURE!   **:)**

**Comment by aanon4** [comment]
Okay, backup for review after a few fixes.

**Review by ab7pa — APPROVED** [review]
Perfect!  That fixes all the issues.  Thanks very much, @aanon4 Tim!

**Pull request merged**
