### PR TITLE
Wifisignal improvements

### PR DESCRIPTION
**Pull request by aanon4**

### CODE REVIEW

**Review by ab7pa — COMMENTED** [review]
This fixes the reported issue.  Because you take the level back to zero, it will draw lines to zero on the graph periodically.

**Comment by aanon4** [comment]
Just verifying you update both ends?

**Comment by ab7pa** [comment]
Ah...  no, just the end I'm using for the graph.  Will update the other and report back.  THX

**Comment by aanon4** [comment]
Can I reach the nodes you're testing?

**Comment by ab7pa** [comment]
Installed the new wifisignal.ut on both ends, and the graphs look great now -- no zero-level values are plotted over the entire 5 min span.

**Pull request merged**
