### PR TITLE
Password visible toggle

### PR DESCRIPTION
**Pull request by aanon4**
Add toggle for password visibility. Open to better design.
pwdviz

### CODE REVIEW

**Comment by aanon4** [comment]
https://github.com/aredn/aredn/issues/463

**Comment by aanon4** [comment]
@K6AH asks if someone could do a security review.

**Review by ab7pa — COMMENTED** [review]
Works as intended on my test nodes.  Simply changes the input display type from _password_ to _text_ and back when toggled.  All other security features remain unchanged.

**Comment by aanon4** [comment]
So this field never shows what the password is, only what has been typed in the box. And this page is protected so only someone with the password can view it.

**Comment by K6AH** [comment]
Got it.  That's the answer I was looking for.  Thanks

**Review by dman776 — APPROVED** [review]
looks ok

**Comment by nc8q** [comment]
Tim: Thanks.
I would love to have this on the Client Wi-Fi password entry box.
3s, Chuck

**Comment by aanon4** [comment]
@nc8q This is already on that field too.

**Pull request merged**
