### PR TITLE
Lua Services

### PR DESCRIPTION
**Pull request by aanon4**
Migrate a set of services currently in Perl and SH into Lua, and mange using a central Lua manager to better coordinate the operation and to reduce overall memory footprint.

### CODE REVIEW

**Comment by aanon4** [comment]
This is the first of the two PR's we discussed. If someone who isn't me could spin this up on a node to sanity check that'd be fantastic.

**Review by ae6xe — COMMENTED** [review]
rssi_monitor implementation is only handling the horizontal receive chain.   The original also handled the vertical receive chain.  The use cases include single chain devices that generally will be on the vertical polarity, e.g. a bullet with an omni antenna.    The current implementation would not cover this use case.

**Comment by aanon4** [comment]
I had meant to ask you about that but forgot. The Lua API provided only a single piece of information, which I'm assuming (big assumption) is a combined value and that'd work okay? If not I can pull the information the old way like the perl code did.

**Comment by ae6xe** [comment]
I don't know how well the combined value will work.   I know that the symptoms were seen on only one polarity-chain.   If the values from 2 chains are combined, there would be less sensitivity, so we risk it won't trigger when it needs to.  This appears to be a tradeoff of more attention on testing with the current code vs adding the code to handle both receive chains.

**Comment by aanon4** [comment]
I will just go with a two-chain solution because we know that works - thanks!

**Comment by dman776** [comment]
adding the first of the dump_perl project as discussed

**Pull request merged**
