### PR TITLE
vpn send details in new browser window fixes #218

### LINKED ISSUE #218: Easy improvement to send details feature on Tunnel Server screen?
Can the send details button be set to open a new tab or new window for those of us using web based email clients? When using it, hitting the back button doesn't bring me back to the tunnel server screen so it slows down the administration of tunnel clients.

It should be a pretty easy tweak to line 461 of https://github.com/aredn/aredn/blob/main/files/www/cgi-bin/vpn

Current:
` print "<td rowspan='2' class='tun_client_center_item tun_client_mailto'><a href='mailto:?subject=AREDN%20Tunnel%20Connection&body=Your%20connection%20details:%0D%0AName:%20$name%0D%0APassword:%20$passwd%0D%0ANetwork:%20$fullnet%0D%0AServer%20address:%20$dns'></a></td>" unless($val eq "_add");`

New window/tab for details:
` print "<td rowspan='2' class='tun_client_center_item tun_client_mailto'><a href='mailto:?subject=AREDN%20Tunnel%20Connection&body=Your%20connection%20details:%0D%0AName:%20$name%0D%0APassword:%20$passwd%0D%0ANetwork:%20$fullnet%0D%0AServer%20address:%20$dns' target='_blank'></a></td>" unless($val eq "_add");`

Thanks,
KM6SLF

### PR DESCRIPTION
**Pull request by ab7pa**
fixes #218
My ide likes to remove extraneous blanks, but the only functional change to the file is on line 461 where "target='_blank'" has been added.

### CODE REVIEW

**Comment by aanon4** [comment]
Looks good.

**Review by dman776 — APPROVED** [review]
looks good

**Comment by wck86** [comment]
Thanks!

**Comment by aanon4** [comment]
Fix propagated to lua version

**Pull request merged**
