### PR TITLE
Remove functional use of :has css so we can support older browsers.

### PR DESCRIPTION
**Pull request by aanon4**
Some cosmetic use remains.

### CODE REVIEW

**Comment by jimsky7** [comment]
I am unfamiliar with when dailies are deployed. Installed 20240824-471c6a1 just now on http://aa6ax-twinpeaks-nsm5-ch177.local.mesh/a/status and the Login icon does not react to click. Later today I can look at the CSS. But maybe this isn't even the 'daily' that has the fix? I did the install using the node's old admin page. In Firefox I can 'inspect' the menu DIV and set 'display:block' at which point the Login menu appears, I can click and enter admin mode. So the only thing malfunctioning is the click on the icon. Hoping that I just don't yet have the version with the new code...

**Comment by aanon4** [comment]
Unfortunately, due to GitHub failing at 2am this morning, the build is delayed and wont be available for another hour. You will need to refresh and redownload then.

**Comment by jimsky7** [comment]
thx I understand this is not the build.

HOWEVER I (still) see an error that you'd want to address:

The FF debugger shows a 404 on this request:

http://localnode.local.mesh/a/css/admin.css.ac6e2dc517b471c95af9f00da2b92fc3

AND:

GET http://localnode.local.mesh/a/css/admin.css.ac6e2dc517b471c95af9f00da2b92fc3 net::ERR_ABORTED 404 (Not Found)

AND it claims there's a syntax error in this line "status:66":

        if (e.detail.requestConfig.triggeringEvent?.type === "click") {

in this block of code:

        if (e.detail.requestConfig.triggeringEvent?.type === "click") {
            const ismodal = e.detail.target?.id === "ctrl-modal";
            setTimeout(_ => {
                if (document.body.classList.contains("htmx-request")) {
                    logo.classList.add("animate");
                }
            }, ismodal ? 1000 : 500);
            if (ismodal) {
                setTimeout(_ => {
                    if (!e.detail.target.open) {
                        e.detail.target.showModal();
                    }
                }, 200);
            }
        }

No idea whether either of those is important or not, and also as you've said, my browser is a couple of years old. So Fyi.

**Comment by aanon4** [comment]
The 404 are expected and are related to how resource loading is optimized.
The syntax error - sigh - I guess the browser's JS is also rather old.

**Comment by aanon4** [comment]
https://github.com/aredn/aredn/pull/1393

**Pull request merged**
