### PR TITLE
Improve xlink integration

### PR DESCRIPTION
**Pull request by aanon4**
Improve integration of external links (xlinks).
These are the extra vlan links, often to non-aredn radios. These changes better integrate the links into the other
subsystems, including how they look on the Mesh page, and allows LQM to monitor them.

### CODE REVIEW

**Comment by aanon4** [comment]
No love or feedback? :-(
If it makes anyone feel better, this code is running on a test link up here in SF (non-AREDN radios about 25 miles apart) and working well.

**Review by Orv — COMMENTED** [review]
Unsure how to test it...

**Comment by aanon4** [comment]
Fair point. It should have no visible effect when not in use - which is what most users would see.

**Review by Orv — COMMENTED** [review]
No, I mean how do I test it?  What needs to be installed?

**Comment by ab7pa** [comment]
@aanon4 Tim, sorry I’ve been preoccupied this week and haven’t loaded your new xlink code.  One thing I noticed in **05-xlink**, there is an initial character in front of the opening comment characters.
  `O--[[`

I loaded the PR and tested on my desktop nodes — no crosslinks to actually see here, but the node rebooted and ran correctly.  The only change I made was to remove that initial character from the **05-xlink** file, and everything worked as advertised.  All of the pages came up and functioned just fine.

**Comment by aanon4** [comment]
@ab7pa Thanks for catching that! Somehow I messed up the #! at the top of the fix - fixed now.

**Review by ab7pa — APPROVED** [review]
Tested and works as designed.  THX @aanon4 Tim!

**Comment by ab7pa** [comment]
I loaded and tested this and it should be ready to go.  THX

**Review by dman776 — APPROVED** [review]

**Review by dman776 — APPROVED** [review]

**Review by dman776 — APPROVED** [review]

**Pull request merged**
