### PR TITLE
LQM fixes 2

### PR DESCRIPTION
**Pull request by aanon4**
Improve LQM quality measurement and reboot tolerance.
    Rebooting/Reflashing remote nodes was dragging down SNR and Quality
    measurements when we'd do better ignoring these events.
Use arping to test latency with neighbor nodes.
    This is better than using an IP level ping as it doesn't require the remote node to have a route
    back to this node and also ignores any firewall level blocks.

### CODE REVIEW

**Comment by aanon4** [comment]
Apologies - merge history is a little messy.

**Comment by aanon4** [comment]
I promise I've finished for now. Have a few local people itching to update but I've put them off until this goes into the nightly.

**Review by ae6xe — APPROVED** [review]
looks good.

**Review by dman776 — APPROVED** [review]
Looks good

**Pull request merged**
