### PR TITLE
Format Uptime as String

### PR DESCRIPTION
**Pull request by ab7pa**
Format uptime as a string with values for days, hours, minutes, and seconds.
Added this to /usr/lib/lua/aredn/info.lua in the model.getUptime function.

### CODE REVIEW

**Comment by ab7pa** [comment]
I just found there is a secondsToClock function in utils.lua which does the same thing.  I'm going to take advantage of that function rather than reproduce the code in info.lua

**Comment by ab7pa** [comment]
Okay, the secondsToClock function does what is needed.  THX

**Comment by dman776** [comment]
In this case, it's intentional.  The presentation should format into the locale specific format.  Ie.  If my browser locale is US English, it should format as days hr:man:sec, but other locales may be different.

**Comment by ab7pa** [comment]
Okay, thanks @dman776 .  In the newui I worked with today it shows up simply as a number of seconds (upsecs) without any formatting, so it looked like it needed some help.  If I'm understanding you correctly, I should close this PR as unnecessary.  Much appreciated.

**Review by dman776 — APPROVED** [review]
actually, after re-consideration, this is NOT a "time" value.   it is elapsed time.   i think it ok to put this conversion here instead of the frontend.

**Pull request merged**
