### PR TITLE
Add build target for Meraki MR16 devices.

### PR DESCRIPTION
**Pull request by AbortRetryFail**
Added support for Meraki MR16. 

See also: https://github.com/aredn/aredn/issues/103

### CODE REVIEW

**Review by ae6xe — CHANGES_REQUESTED** [review]
Let's go ahead and change 'unknown' to 'stable'.  this is consistent with support for other new devices.  Because it has full support from OpenWRT we have confidence. The AREDN specific features were tested.

**Review by ae6xe — APPROVED** [review]
Looks good.

**Comment by kg5eiu** [comment]
I am willing to try out the code - However, I am not sure how to get the code loaded onto the MR16 - any pointers or links ?   I just picked up two of these off ebay so ready to give it a try.

**Comment by AbortRetryFail** [comment]
I had installed OpenWrt 19.07 on all of mine prior and used the sysupgrade image to install AREDN.
https://openwrt.org/toh/meraki/mr16
https://parkercs.tech/installing-openwrt-on-a-meraki-mr16/
 
You'll need a PC with a TFTP server for the files, a TTL serial port, and a few spudgers or old gift cards to open the casing without destroying it.

**Comment by cygeus** [comment]
My Meraki MR16 is running OpenWrt 23.03.4. I used `sysupgrade` to do the upgrade to the latest build for the MR16 [(aredn-3.22.12.0)](http://downloads.arednmesh.org/firmware/aredn-3.22.12.0-ar71xx-generic-mr16-squashfs-sysupgrade.bin).

> root@OpenWrt:/# sysupgrade /tmp/aredn-3.22.12.0-ar71xx-generic-mr16-squashfs-sysupgrade.bin 
Sun Apr  9 12:36:53 UTC 2023 upgrade: Image metadata not present
Sun Apr  9 12:36:53 UTC 2023 upgrade: Use sysupgrade -F to override this check when downgrading or flashing to vendor firmware
Image check failed.

Overriding the check with `sysupgrade -F` starts the flashing process, but results in an error on the first boot:

> \#\# Booting image at bf0a0000 ...
> Bad Magic Number


Any idea what is wrong?

**Comment by AbortRetryFail** [comment]
When I got this working on mine, I used ar71xx because that's what my devices had on them (OpenWrt 19.07)

OpenWrt 20 and later are ath79, which I never tried. It might be possible to build AREDN images for that too.

**Comment by cygeus** [comment]
Indeed, it makes sense to use ath79 nowadays.
I've compiled the latest commit for the Meraki MR16 which went fine and also installed fine on a few devices.
Now it is time for some field testing.

**Pull request merged**
