### PR TITLE
tx power => txpower (typo)

### PR DESCRIPTION
**Pull request by aanon4**
Typo when setting power using iw command
https://github.com/aredn/aredn/issues/249

### CODE REVIEW

**Comment by ab7pa** [comment]
@aanon4 Tim, I applied this fix but for some reason the new value does not persist after a reboot.  Defaults back to highest Tx Power in the dropdown.  Is this a UI issue or something in the backend config save process?

**Comment by aanon4** [comment]
My observation with both the old Perl and new Lua was that hitting apply made the value stick until reboot but unless you hit save it would not persist across reboots even with the Perl code. Is this not what you see?

**Comment by ab7pa** [comment]
No, I select a new value from the dropdown list, click APPLY, then click SAVE CHANGES, then click REBOOT.  After reboot it has reverted to the old value.

**Review by dman776 — APPROVED** [review]

**Comment by aanon4** [comment]
Fixed in https://github.com/aredn/aredn/pull/252

**Pull request merged**
