### PR TITLE
Migrate advancedconfig page to lua

### PR DESCRIPTION
**Pull request by aanon4**
New lua version of this page. The old page has been renamed with .pl extension

### CODE REVIEW

**Comment by ab7pa** [comment]
@aanon4 Tim, this new version works really well on my test node after I removed the .lua extension on references to other pages.  I noticed on line 392 the word _Hipper_ and assume it should be _Upper_?  Also, for some reason the two rows for aredn.@tunnel[0].maxclients & maxservers are not showing up on my lua page, but they appear just fine on the perl version of the page.  Makes me wonder if the test may be failing for whether tunneling is installed/running?

**Comment by aanon4** [comment]
Well the typo was easy enough. On the maxclient/maxservers .. are these the only values not showing up? Everything else looks okay?

**Comment by ab7pa** [comment]
I don't have a way to test the values for USB passthrough or PoE passthrough, so I'm not sure about them, but everything else appears correctly.  Well done!

**Comment by aanon4** [comment]
Thanks. Should now be fixed.

**Comment by ab7pa** [comment]
Perfect! The tunnel rows are now displayed.  Nice!

**Review by dman776 — APPROVED** [review]
Tested ok by steve

**Pull request merged**
