### PR TITLE
Added support for group alert messages

### PR DESCRIPTION
**Pull request by hickey**
These changes are to address the feature request that I put forward in #872. 

At this point the changes are untested, but they appear that they would work. If it is possible to build an AREDN firmware from this branch, then I would be very happy to test the changes on one of my nodes to validate that the functionality is working.

### CODE REVIEW

**Comment by ab7pa** [comment]
I have two suggestions.  First, make the _Alert Groups_ feature part of the "AREDN Alert Settings" **category** so they appear along with all of the other Alert Settings.  Second, the grouping feature is actually a subset of **Local Messages** so they should be under that code section rather than appending them separately at the end.  I'm attaching two files here:  one shows the Alert Groups as part of the _AREDN Alert Settings_ category, and the second shows what the entire **aredn_message.sh** script could look like with the groups as part of the _Local Message_ section of code.  I have tested both of these attached files on my Alert node and they work as you envisioned.

[advancedconfig-alertgroup.txt](https://github.com/aredn/aredn/files/11959955/advancedconfig-alertgroup.txt)

[aredn_message.sh.txt](https://github.com/aredn/aredn/files/11959959/aredn_message.sh.txt)

**Comment by ab7pa** [comment]
Here is what the Alert Group code I suggested above looks like on one of my alert subscriber nodes:

**Comment by hickey** [comment]
Ah. I was not looking at the fields close enough. The category field I was thinking that it was a field name. The intention was to keep the setting with the other alert fields. I will get the category field updated to get it included in the alert section. 

Your screen capture off one of your nodes is precisely what I was envisioning also. 

Are there any GitHub actions out there that I can add to my fork to build the sysimage file so that I can install and test changes to insure that things are working?  Actually with these changes the amount of updates are easy and I can go update one of my nodes (probably similar to what you did). It would be nice to have a way to generate the sysimage from a branch so that bigger changes can be tested easily.

**Comment by hickey** [comment]
I have updated `advancedconfig` and  I am still working on `aredn_message.sh`. I have refactored out all the `wget` commands into a function since it is all the same operation and makes the code a bit more readable. I am looking at writing the final alert text to the file at same time as that would clean up a bit more code too. 

I have created https://github.com/aredn/documentation/pull/273 for documenting this feature.

**Comment by hickey** [comment]
@ab7pa I have completed the updates to `aredn_message.sh`. Take a look and see if you see any issues. I have tested the local and group alerts and can not fore see any issues, but I am unable to test the AREDN messages. Ideally they should be handled in the same manner as before.

**Review by ab7pa — APPROVED** [review]
Looks good, @hickey   And thanks for the corresponding documentation update too.

**Review by aanon4 — APPROVED** [review]
Good to go.

**Pull request merged**
