### PR TITLE
Add nanobeam ac gen1 xc

### PR DESCRIPTION
**Pull request by aanon4**

### CODE REVIEW

**Review by ae6xe — COMMENTED** [review]
did the pwroffset get pulled from /etc/board.info under AirOS?     Not yet known to iw, but all the prior nanobeam's have hard xmit power offsets:
root@AE6XE-HapAC2-QTH:~# grep -i nanobeam /usr/share/libiwinfo/devices.txt
0x168c 0xffff 0x0777 0xe2c2   10      0  "Ubiquiti" "NanoBeam M2 Int" /* airOS XW */
0x168c 0xffff 0x0777 0xe812    6      0  "Ubiquiti" "NanoBeam M2 13" /* airOS XW */
0x168c 0xffff 0x0777 0xe815    4      0  "Ubiquiti" "NanoBeam M5 16" /* airOS XW */
0x168c 0xffff 0x0777 0xe825    4      0  "Ubiquiti" "NanoBeam M5 19" /* airOS XW */

**Comment by aanon4** [comment]
I dont have the device and it is not running AREDN (unsupported). How do we get that information?

**Comment by ae6xe** [comment]
Reload the AirOS firmware back to factory.  Log in with "ssh ubnt@192.168.1.1" (check my IP address, from memory).  scp or cat /etc/board.info:

board.sysid=0xe005
board.name=NanoStation M5
board.shortname=N5N
board.subtype=
board.hwaddr=00156DE4C277
board.reboot=30
board.upgrade=150
board.phycount=2
radio.1.name=
radio.1.shortname=
radio.1.bus=pci
radio.1.subsystemid=0xe005
radio.1.subvendorid=0x0777
radio.1.txpower.max=27   **<- in AREDN radio.json it would be  22  (where 22 + power.offset = 27) for this example**
radio.1.txpower.offset=5
radio.1.antennas=1
radio.1.def_antenna=4
radio.1.antenna.1.id=4
radio.1.antenna.1.name=Combined
radio.1.antenna.1.gain=16

**Comment by aanon4** [comment]
Okay. Looks like I need to do this for many devices.
Can we merge this then I'll prepare another PR to update all the relevant power offset?

**Review by ae6xe — APPROVED** [review]
merging in with expectation of forthcoming PR to resolve offset (and review max power is also correct) on multiple ubiquiti devices.

**Pull request merged**
