### PR TITLE
Line up the columns on the mesh display

### PR DESCRIPTION
**Pull request by aanon4**
Line up the columns on the mesh display.

### CODE REVIEW

**Comment by ab7pa** [comment]
I like the columns lined up with each other, but I'm not thrilled with the _OLSR Entries_ and _Previous Neighbors_ taking up space on the right side.  Can't we just delete those two sections from the **Mesh Status** page?  IMHO they really don't add any value, but I'd like to understand why they're required if others think they're essential.

**Comment by aanon4** [comment]
Screen Shot 2022-10-24 at 8 59 29 AM

**Comment by aanon4** [comment]
So people can see what the proposed layout looks like with this change. Happy to remove the OLSR part, but the Pervious Neighbors need to be somewhere on this page still.

**Comment by ab7pa** [comment]
Some Current & Remote node names are now wrapping if they are too long.  Also, there are some node names with a `dtdlink.` prefix that could be filtered off -- and tactical names have a `.local.mesh` suffix that could be filtered off.

**Comment by ab7pa** [comment]
Example of prefix/suffix and wrapping

**Comment by ab7pa** [comment]
As long as the nodenames are reasonably short the Previous Neighbors width should work.  When the nodenames get too long then they will definitely wrap.
Screen Shot 2022-10-25 at 11 56 58 AM

**Review by ab7pa — APPROVED** [review]
Nice to line up the columns on all tables.  Works as designed.  Thanks, @aanon4 Tim.

**Review by dman776 — APPROVED** [review]

**Pull request merged**
