### PR TITLE
Set tunnel weight to 1 and provide UI to change it.

### PR DESCRIPTION
**Pull request by aanon4**

### CODE REVIEW

**Comment by KenHorse** [comment]
Would being able to set the actual weight value be an advantage in some circumstances?

**Comment by aanon4** [comment]
> Wouldn't being able to set the actual weight value be an advantage under some circumstances, maybe even on a per node basis?

I have mine set to 3 by default to make my tunnel look super unappealing.

**Comment by KenHorse** [comment]
Editing a config file?

**Comment by aanon4** [comment]
If you look at this PR you'll see what it does. The mechanism has existed for a while, just no UI to change it.

**Comment by ab7pa** [comment]
Screenshot 2023-09-19 at 12 24 05 PM

**Comment by KenHorse** [comment]
Ahhhh, I should pay more attention!

**Comment by KenHorse** [comment]
Although technical, that is a GUI <g>

**Comment by aanon4** [comment]
To be fair, that UI is this PR, so it's not in the build just yet.

**Comment by aanon4** [comment]
However, what the UI changes already exists in the release build, so you can change it from the command line already.

**Comment by KenHorse** [comment]
Is it a specific command or just editing a config file? (I'm old school - vi for me!)

**Comment by aanon4** [comment]
Might be best to wait on this UI landing in the nightly build.

**Comment by KenHorse** [comment]
RR, will patiently wait

**Review by mathisono — COMMENTED** [review]
add the readout of etx value in the /lqm status page for Neighbors.

**Comment by KenHorse** [comment]
Was the removal of the SEARCH feature in the Mesh Status page planned or an undocumented feature?

**Comment by ab7pa** [comment]
It's not removed...  just cleaned up.  See the docs here:
https://docs.arednmesh.org/en/latest/arednGettingStarted/mesh_status.html#mesh-status-display-sections

**Comment by KenHorse** [comment]
Yea, I saw that after I posted so I did a ninja delete....sorry

**Pull request merged**
