### PR TITLE
Ath9k - no error accounting

### PR DESCRIPTION
**Pull request by aanon4**
To follows https://github.com/aredn/aredn/pull/712

Calculate the tx rate the same way for both ath9k and ath10k drivers so we have consistent reporting.

### CODE REVIEW

**Comment by aanon4** [comment]
@ae6xe This uses the same mechanism for both ath9k and ath10k devices. I'll leave it up to you whether to commit or close.

**Review by ae6xe — CHANGES_REQUESTED** [review]
remove the rateL and rateS tables, no longer in use.

**Comment by aanon4** [comment]
@ae6xe You probably need to push it again as there was a merge conflict which I fixed.

**Review by ae6xe — APPROVED** [review]
looks good.

**Pull request merged**
