### PR TITLE
Remove potentially problematic copying of /etc/config.mesh/aredn

### PR DESCRIPTION
**Pull request by aanon4**
Remove the potentially problematic 'filecopy("/etc/config/aredn", "/etc/config.mesh/aredn")'

/etc/config.mesh/aredn sometimes gets truncated, although reproducing it is difficult. This
is one of the few (only?) places this file is mindlessly written to, so instead use cursors to update it.

https://github.com/aredn/aredn/issues/253

### CODE REVIEW

**Comment by aanon4** [comment]
https://github.com/aredn/aredn/issues/253

**Comment by aanon4** [comment]
I promise this is the last one today :-) @dman776 @ae6xe

**Comment by ae6xe** [comment]
@aanon4 We're just trying to stay out of the way, to move all the high quality effort you are putting in forward!   You really don't need our review to get this stuff in!  I am humbled and in awe of the contribution you are making and can only hope that when I retire, I am able to do the same.  ...It will be another 5+ years before I retire :) .

**Review by ae6xe — APPROVED** [review]
looks good!

**Comment by aanon4** [comment]
@ae6xe Thanks! I'm lucky enough to have the time, and good people to work with.

**Pull request merged**
