### PR TITLE
Lqm2

### PR DESCRIPTION
**Pull request by aanon4**
Towards the end of working on the original LQ, it became clear that various groups run DtDs and Tunnels over radio links. And while we don't have direct access to a lot of those radio metrics, we can at least measure the quality of them. So this extends LQM to monitor all links using whatever data we can.

### CODE REVIEW

**Comment by aanon4** [comment]
This is one of the new behaviors. The DtD link is clearly not a local connection to the other node (being 33 miles away) so LQM no longer assumes it hardwired and reliable. If it was close you'd see the old behavior.

**Comment by ab7pa** [comment]
Got it!  Thanks for the clarification.

**Review by ab7pa — APPROVED** [review]
Tested between seven nodes and works as designed.  Thanks, @aanon4 Tim.

**Comment by ae6xe** [comment]
@ab7pa  wrote, "Should collocated DtD nodes have their RF status set to blocked - dtd instead of idle? I'm not clear on which would be correct. THX" 

Yes, I think so.   The dtdlink path is optimal and redundant RF path is not necessary.   No need for OLSR to show this duplicate (and higher cost) route path across the mesh network.   Although, if the dtdlink path fails, we would want the RF path to not be blocked.

**Comment by aanon4** [comment]
My reasoning for long DtD not to be treated as equal to short DtD is the the long ones are also RF and so subject to the vagary that come with. In these cases I thought it best to leave it to OLSR to pick a route (assuming they're not blocked for other reasons).

**Comment by ab7pa** [comment]
Your explanation above cleared it up for me, Tim.  In the environment you have for all your testing you've seen many types of links that I have not seen here.  And I think you're correct to distinguish between long vs. short DtD links.  Makes sense because some of them are over radio.

**Review by Orv — APPROVED** [review]

**Review by ae6xe — APPROVED** [review]
looks good.

**Pull request merged**
