### PR TITLE
Fix support for lhgg-5acd-xl

### PR DESCRIPTION
**Pull request by aanon4**

### CODE REVIEW

**Review by ae6xe — COMMENTED** [review]
Wouldn't radio.json also need an update?  The model string is the same?

**Comment by aanon4** [comment]
I just missed these on my first attempt sometime back. The rest was already in place.

**Review by ae6xe — APPROVED** [review]
looks good.

**Comment by kearneyjf** [comment]
Installed Build 2423 on my MikroTik RBLHGG-5acD-XL. Solved the problem.
Thanks very much for the quick fix.
John, KM6ZJT

**Pull request merged**
