### PR TITLE
group Mesh RF info if wifi_enabled

### PR DESCRIPTION
**Pull request by ab7pa**
If wifi_enabled then group all the relevant _Mesh RF_ information with the IP address.

**Status display with Mesh RF enabled and having RF links:**

**Status display with Mesh RF enabled but without RF links:**

**Status display with Mesh RF disabled:**

### CODE REVIEW

**Review by Orv — APPROVED** [review]
A small but useful tweak to the Node Status page

**Comment by aanon4** [comment]
@ab7pa I dont suppose you fancy fixing the somewhat arbitrary casing of these words while you tweaking this bit? (this counts as hijacking this PR so please ignore if you don't want to :-))

**Review by aanon4 — DISMISSED** [review]

**Comment by ab7pa** [comment]
Fixed various minor issues with the Status page (colons, semicolons, case, etc).

**Comment by ab7pa** [comment]
Thanks to everyone for the many suggestions for improvement on this **Status** page.  Definitely a team effort.  THX

**Review by Orv — APPROVED** [review]
More nice little tweaks - works fine.

**Review by dman776 — APPROVED** [review]

**Pull request merged**
