### PR TITLE
Improve antenna settings messaging

### PR DESCRIPTION
**Pull request by aanon4**

### CODE REVIEW

**Comment by K5RA** [comment]
I think Elevation should be between -90 and +90 degrees  from the horizontal.  I am not able to think of an antenna mount where this would be appropriate.

**Comment by K5RA** [comment]
Excellent.

**Comment by caseydiers** [comment]
@aanon4 
I also proposed reordering them so that azimuth and elevation were together:

- height
- azimuth
- elevation


 I find it to be more intuitive, than the current ordering of 

- azimuth
- height
- elevation

**Comment by aanon4** [comment]
Is there a compelling case for any particular order? Perhaps how it's ordered in other software, or some generally accepted practice I can look at?

**Pull request merged**
