### PR TITLE
update GL-inet supported devices list

### PR DESCRIPTION
**Pull request by cTurtle98**
I did the same thing I did to the mikrotik supported devices list to the gl-inet supported devices list

### CODE REVIEW

**Comment by cTurtle98** [comment]
@aanon4 what do you think of this?

**Comment by aanon4** [comment]
@cTurtle98 Unfortunately I dont have the ability to accept this. Looks okay to me though.

**Comment by cTurtle98** [comment]
@ae6xe you approved my update of the mikrotik list. do you like this update to the gl-inet list?

**Review by ae6xe — APPROVED** [review]
looks good.

**Pull request merged**
