### PR TITLE
Optionally include static routes (and preserve them across upgrades)

### PR DESCRIPTION
**Pull request by aanon4**
Provide a more standard way to include extra static routes which will be preserved across reboots and upgrades.

https://github.com/aredn/aredn/issues/482

### CODE REVIEW

**Comment by ae6xe** [comment]
Suggest to have an empty include file with comments of purpose and example entry, so users know what format to use (openwrt UCI).  Could even have a URL to this openwrt documentation.  

Any consideration (maybe future) UI ability to add the static route?     Otherwise, this is ready to merge in main?

**Comment by dman776** [comment]
looks good to me.

**Comment by aanon4** [comment]
The reason its draft is I'm away from home until Wednesday so can't run proper testing on this. If someone wants to do a build and make sure it works then I can make it ready.

**Review by ae6xe — APPROVED** [review]
looks good.

**Pull request merged**
