### PR TITLE
Handle missing ip and more general RF/DTD identification

### PR DESCRIPTION
**Pull request by aanon4**

### CODE REVIEW

**Comment by ae6xe** [comment]
checklist I'm sure you're already considering to differentiate in the pipeline:
1) tun
2) RF on different channel (future multiple RF mesh interface devices)

**Comment by aanon4** [comment]
@ae6xe Tested by @ab7pa. This was just an addition for hidden node detection which assume a few things which are, apparently sometimes, not true.

**Review by ab7pa — APPROVED** [review]
Tested on a node with previous issues and this PR fixed those issues.  Thanks, @aanon4 Tim!

**Review by ae6xe — APPROVED** [review]
Looks good.

**Comment by ae6xe** [comment]
@aanon4 I'm getting a not mergable message.   These must have gotten entered in a different order.

**Pull request merged**
