### PR TITLE
add traceroute and remotenodes to api

### PR DESCRIPTION
**Pull request by dman776**
traceroute, remotenodes to api

### CODE REVIEW

**Review by r1de — APPROVED** [review]
looks ~~ok~~ pretty awesome to me.
That'll be useful!
If you didn't get a "Bad Gateway" when testing it, then it is probably just fine!

**Review by ab7pa — CHANGES_REQUESTED** [review]
I tested this PR on top of all previous ones in the queue (PR112 & PR113) and it worked well, with a couple of tweaks.  PR113 removes hostname case manipulation, so this PR114 should not uppercase the hostname (info.lua lines 331 and 551).  Also utils.lua should probably use` %d+` on line 277 to catch one or _more_ digits in the **mid** prefix.  Then in api the `name:match` should have lowercase _mid_ on line 135.

**Review by ab7pa — APPROVED** [review]
I tested this PR on top of NB368 today and it worked well.

**Comment by ab7pa** [comment]
Is there more to do on this PR or is it ready to merge?  Looks fine to me.

**Pull request merged**
