### PR TITLE
Fix AirRouter

### PR DESCRIPTION
**Pull request by aanon4**
A bit of a guess as I dont have a device to test this on.

### CODE REVIEW

**Review by dman776 — COMMENTED** [review]
I've got one to test this on.   Do you have a build?  If not I'll build one

**Comment by aanon4** [comment]
I can quickly make one for you and send it over if you want?

**Review by dman776 — APPROVED** [review]
tested ok on my Airrouter HP

**Comment by dman776** [comment]
fixes #687

**Pull request merged**
