### PR TITLE
Lua page: Admin

### PR DESCRIPTION
**Pull request by aanon4**
Migrate Admin page to Lua + associated upgrade script.
Also:
+ Add the lua manger to the updatectlservices script
+ Gracefully fail the tunnel startup scripts

Note: This is the last of the perl. Once this is merged, no perl will be used by any of the software on the node. This does not remove the perl code, leaving it in place for debugging, and for removal by a subsequent PR.

### CODE REVIEW

**Review by ae6xe — COMMENTED** [review]
couple thoughts:
1) good time to rename "bbhn-postupgrade" to "aredn_postupgrade"?  bbhn is somewhat of a competitive, but dead, group nowadays.
2) for all the log files created -- are these added to be included in the support data download file, to help do remote support?

**Comment by aanon4** [comment]
1. Done
2. Yes, supporttool was already updates with the new log files

**Review by ae6xe — APPROVED** [review]
all looks good.

**Comment by ae6xe** [comment]
intended to be a 'draft' PR still?

**Comment by aanon4** [comment]
I'm happy for it to drop into tonight's Nightly if you folk are.

**Pull request merged**
