### PR TITLE
Add azimuth, elevation and antenna information

### PR DESCRIPTION
**Pull request by aanon4**
It's a long requested feature to add the azimuth information. This is useful when setting up nodes and working out which current nodes are pointing towards you. But without the beamwidth information that didn't seem as useful as it could be. Rather than forcing people to enter that, instead encode it with each radio which has built-in antennas, and allow selection from a database of external antennas.

Note. Many more antennas to add still.

https://github.com/aredn/aredn/issues/943

### CODE REVIEW

**Comment by Orv** [comment]
What format do you need antenna information in?

**Comment by aanon4** [comment]
Antenna information looks like this:
```
{
          "model": "AM-9M13-120",
          "description": "airMAX 900 MHz, 13 dBi, 120&deg; Sector",
          "gain": 13,
          "beamwidth": 120
}
```
For external antennas, it lives in the /etc/antennas.json file. For builtin antennas, it lives in the /etc/radios.json file. For example:
```
"mikrotik hap ac2": {
    "wlan0": {
      "maxpower": 27,
      "bandwidths": [ 5, 10, 20 ],
      "antenna": {
        "description": "2.5 dBi Omni",
        "gain": 2.5,
        "beamwidth": 360
      }
    },
    "wlan1": {
      "maxpower": 26,
      "bandwidths": [ 10, 20 ],
      "antenna": {
        "description": "2.5 dBi Omni",
        "gain": 2.5,
        "beamwidth": 360
      }
    }
  }
```

**Comment by Orv** [comment]
KP Performance dish.   Performance info for use on 2, 3 and 5 GHz

{
          "model": "UB24EWIFIDBI",
          "description": "KP Performance Antennas Dish@2GHz",
          "gain": 19,
          "beamwidth": 12
}

{
          "model": "UB24EWIFIDBI",
          "description": "KP Performance Antennas Dish@3GHz",
          "gain": 21,
          "beamwidth": 9
}

{
          "model": "UB24EWIFIDBI",
          "description": "KP Performance Antennas Dish@5GHz",
          "gain": 25,
          "beamwidth": 6
}

**Comment by aanon4** [comment]
@Orv Added.

**Comment by Orv** [comment]
{
          "model": AS24G17B90MS-KU",
          "description": "Altelix 2.4 GHZ; Sector",
          "gain": 17,
          "beamwidth": 90
}

**Comment by Orv** [comment]
{
          "model":AS5158G18B65Ms-NF",
          "description": "Altelix 5 GHZ; Sector",
          "gain": 18,
          "beamwidth": 65
}

**Pull request merged**
