### PR TITLE
Add a note about the USB150 device

### PR DESCRIPTION
**Pull request by aanon4**

### CODE REVIEW

**Review by dman776 — CHANGES_REQUESTED** [review]
it's the AR150 that I have that doesn't reboot.  I havent tried the USB150

**Comment by aanon4** [comment]
Oh! I've been trying the USB150 and it doesn't reboot - so maybe it's both?

**Comment by aanon4** [comment]
This was in relation to https://github.com/aredn/aredn/issues/645 which I dont think will be fixed anytime soon.

**Comment by aanon4** [comment]
@dman776 do i need to add the note to the AR150 also?

**Review by dman776 — APPROVED** [review]

**Pull request merged**
