### PR TITLE
new SUPPORTED_DEVICES.md format

### PR DESCRIPTION
**Pull request by dman776**
proposed new format for discussion

### CODE REVIEW

**Comment by VA2XJM** [comment]
For machine reading uses OR markdown cut/paste, the status column should not be left empty. It should indicate something like "Actual" or "Active" or "Current".

**Comment by VA2XJM** [comment]
It should also be markdown formated as a table, It would make it a very handy format. I missed that on first pass.

**Comment by ab7pa** [comment]
Could we change the "new" _Status_ to "nightly" and then in the _Notes_ say that this device is supported only in the nightly build firmware at this time?  For a device with _Stability_ of "untested" maybe we could say _Stability_ is "unknown" and Status is "untested"?  What would you think of eliminating the Meraki device, since it is not supported in these Nightlies or in future Stable releases?

**Comment by dman776** [comment]
it *IS* a markdown table now...
For standardized terms, what do you think about:

- Stability: "Unknown", "Stable", "Bricked" and/or "Unstable"
- Status: "Released", "Nightly"

This way, when we prepare the "release" PR, one step would be to simply change all the "Nightly" to "Released" in this file.

**Comment by ab7pa** [comment]
Sounds good to me. Good idea.  And the MD table looks fine to me.

**Comment by aanon4** [comment]
Also seems good to me.

**Comment by ab7pa** [comment]
I think these GL.iNet devices are "unknown" and "nightly" only.
```
GL.iNet GL-AR300M w/ 128MB NAND | 2 | ath79 | nand | gl-ar300m | 64MB | unknown | released
GL.iNet GL-AR750s (slate) | 2 | ath79 | nand | gl-ar750s | 128MB | unknown | released
GL.iNet GL-E750 | 2 | ath79 | nand | gl-e750 | 128MB | unknown | released
```

**Review by ab7pa — APPROVED** [review]
I think this looks good.  Thanks, Darryl
Is there any way to display this table in Drupal (arednmesh.org) exactly as it's being displayed here in GitHub?  The current Drupal version is very difficult to read.

**Pull request merged**
