### PR TITLE
add ntp update period to basic setup page

### PR DESCRIPTION
**Pull request by ab7pa**
Allow users to set the NTP update period from a dropdown on the Basic Setup UI

Screen Shot 2022-09-21 at 10 58 49 AM

### CODE REVIEW

**Comment by aanon4** [comment]
Needs a way to persist this setting across upgrades.

**Comment by ab7pa** [comment]
Upon **upgrade** the _update-clock_ script defaults to the _cron.daily_ location, so /www/cgi-bin/setup also defaults to _daily_.  If you later change the value to _hourly_, that setting will persist across reboots.  I'll work on after-upgrade persistence in a subsequent PR if that is agreeable.  If not, I completely understand and will keep this as Draft until I get that working.

**Comment by aanon4** [comment]
I think it probably needs to be part of this.
Take a look at "files/etc/uci-defaults" which contains a set of scripts which are executed after each upgrade. You could probably add something here to do what you need.

**Comment by ab7pa** [comment]
Have included persistence of the new setting across upgrades now.  Please let me know if there is feedback or suggested changes that would make this small feature more efficient, etc.  THX

**Comment by ab7pa** [comment]
As an aside, if people want NTP updates to run continuously then they should [install Tim's meshntpd](https://github.com/kn6plv/meshntpd) package on their nodes.

**Review by Orv — APPROVED** [review]
Tested - works as advertised.

**Review by Orv — APPROVED** [review]

**Review by dman776 — APPROVED** [review]
tested by Orv.

**Pull request merged**
