### PR TITLE
Lua userpages

### PR DESCRIPTION
**Pull request by aanon4**
Basic 4 user pages (status, mesh, scan and signal) in Lua.
These pages do not yet override the current Perl pages but can be accessed by appending ".lua" to the appropriate URLs.
Note: These use library code in PR https://github.com/aredn/aredn/pull/189 so this should not be merged before that PR.

### CODE REVIEW

**Review by ae6xe — COMMENTED** [review]
for rssi_monitor(), the test to run_monitor() will very soon need to ensure it is the ath9k 802.11n driver and not the ath10k 802.11ac/n driver.  Possibly, this same logic is needed for ath10k, if code was reused, may need investigated in the future.   One option is to test the path /sys/kernel/debug/ieee80211/phy{0,1}/ath9k exists.

**Comment by aanon4** [comment]
I picked up one of the compatible radios the other day so I can make the necessary changes and test them when you're ready.

**Comment by ab7pa** [comment]
@aanon4 , this looks perfect in my testing.  The build you gave me including 189 & 190 worked flawlessly on my test node (AR750).  On status.lua I verified that the links for Help and "more details" work fine, and the navigation to Mesh Status, WiFi Scan, and Charts work, as well as the theme selection dropdown.  WiFi Scan worked perfectly. Everything on Charts (signal.lua) worked, including Realtime, Archive, node selection dropdown, SNR sound, and export to jpeg/png. On mesh.lua everything looks and works identically to the original.  From my standpoint, these PRs are good to release into the wild for further testing in nightly builds.  Thanks very much for all your amazing work porting everything to Lua!

**Comment by dman776** [comment]
@aanon4 looks like we now have a few conflicts on this that need to be resolved.

**Comment by aanon4** [comment]
Figured that was likely now. Going to take a look this evening or tomorrow.

**Comment by aanon4** [comment]
And ... a very minor thing it turned out.

**Comment by aanon4** [comment]
Switched the lua pages to be the defaults (still marked with a little Lua labels top/right to aid people looking at this)

**Review by dman776 — APPROVED** [review]
looks good.

**Pull request merged**
