### PR TITLE
bug: fix nill typo

### PR DESCRIPTION
**Pull request by ab7pa**
Fix typo (nill to nil) in pidfile test.

### CODE REVIEW

**Review by ae6xe — APPROVED** [review]
good catch.

**Comment by ae6xe** [comment]
did this fix the spike to 0dBm issue?  What symptoms will go away?

**Comment by ab7pa** [comment]
No, this was totally unrelated to the "spike to zero" issue.  Just happened to catch this _nil_ issue while looking through those two files.

**Comment by ae6xe** [comment]
My only concern is that this would change the behavior in some way.   We presume this would be good.  But possibly, it is bad as this code was ether always run or never run.     @dman776, since you wrote this code originally, would you do a quick review to confirm we should commit this.

**Comment by ab7pa** [comment]
I agree.  Seems like the first part of this test will always pass, since _oldpid_ will never equal _nill_

if (oldpid ~= nill and dir_exists("/proc/" .. oldpid))

**Review by dman776 — APPROVED** [review]
good catch

**Pull request merged**
