### PR TITLE
Simpler deaf node monitor

### PR DESCRIPTION
**Pull request by aanon4**
A proposed, simpler, deaf node monitor. It a node has zero stations associated with it, it will run a wifi scan every 5 minutes until that changes. The scan recovers a node. Running the scan when nothing is associated with the node seems harmless.

### CODE REVIEW

**Review by ae6xe — COMMENTED** [review]
The most common use case, if not all instances, there is always 1 neighbor still communicating and one or more weaker neighbors are filtered out (with the noise floor raised).   If I read this PR correctly, it will only trigger when all neighbor's drop out?

The penalty to regularly trigger a passive scan on one channel should be very low.  The more frequently this is done, these increases the risk of a race condition and impact when people do mesh status and any other features that also do iw commands.   wifi scan or mesh status would be at risk to come back with no data.   I'm not sure if this is something to be concerned about or not.

**Comment by aanon4** [comment]
> The most common use case, if not all instances, there is always 1 neighbor still communicating and one or more weaker neighbors are filtered out (with the noise floor raised). If I read this PR correctly, it will only trigger when all neighbor's drop out?

All the reports on https://github.com/aredn/aredn/issues/460 are for the node going completely deaf, not just losing contact with one instance. That's probably to be expected as I doubt anyone would notice if one of many nodes had disappeared when casually looking at their mesh status. 

> The penalty to regularly trigger a passive scan on one channel should be very low. The more frequently this is done, these increases the risk of a race condition and impact when people do mesh status and any other features that also do iw commands. wifi scan or mesh status would be at risk to come back with no data. I'm not sure if this is something to be concerned about or not.

There's obviously no way to know a user is about to use the 'iw' command in some form. The old code was no different here but perhaps the frequency of its use was different?

In the original issue https://github.com/aredn/aredn/issues/460 people observing all nodes disappearing and if this is happening between runs of the monitor, it wont defect this. Thoughts on how we can change that code to deal with this situation?

**Comment by aanon4** [comment]
One option would be to *just* trigger the scan in this code when transitioning from hearing someone to hearing no one. So it would happen extremely infrequently?

Also, in relation to the current rssi monitor's behavior, we could easily add detecting this specific condition to that code?

**Comment by aanon4** [comment]
Here's an alternate approach https://github.com/aredn/aredn/pull/505

**Pull request closed without merging**
