### PR TITLE
update status page to add additional location information 

### PR DESCRIPTION
**Pull request by wh6av**

### CODE REVIEW

**Comment by dman776** [comment]
For consistency, I prefer that we keep the logo in the upper left

**Review by dman776 — CHANGES_REQUESTED** [review]
Setting should be stored in uci format moving forward.   Put devicelocation in the etc/aredn file and make sure that you add to uci-defaults as well.

**Comment by dman776** [comment]
Also, the devicelocation should also be added to the /www/cgi-bin/api (and don't forget to increment the api version number.)

**Comment by r1de** [comment]
Don't get me wrong, I'm all for more info to be shown, but isn't the lat/lon already shown on the main page (if set)?
And we already have the node description field, would that not be used for a more generic location? ie: `This device is located in Oxnard, Ca.`

Not against the change, just sayin' that it seems redundant is all. :smile:

**Comment by dman776** [comment]
Fair point

**Comment by dman776** [comment]
Any other community comments on this??

**Comment by wh6av** [comment]
Sorry, been busy with work here.  I'll get to it this week.
image

**Review by dman776 — CHANGES_REQUESTED** [review]
needs work to comply with uci storage of info.   remove css changes

**Comment by dman776** [comment]
closing.   no response.  Also, changes would need to be based on the new LUA version of this page.

**Pull request closed without merging**
