### PR TITLE
Fix the pattern used to validate services

### PR DESCRIPTION
**Pull request by aanon4**
Broken service pattern

### CODE REVIEW

**Comment by ab7pa** [comment]
With this olsrd-config edit the /etc/config/services file looks good, but the /var/run/services_olsr file no longer contains any of the local services.  Therefore, the Mesh Status page does not display the services for this node under the Local Hosts section where there should be 11 services listed.
Screen Shot 2022-03-10 at 10 07 20 AM

**Comment by aanon4** [comment]
I think (need more coffee still) that /var/run/services_olsr is generated by OLSR from the information it receives on the network. If services are missing then there's probably an issue with olsrd-config still. Can you post the output from olsrd-config and the old olsrd-config.pl so?

**Comment by ab7pa** [comment]
Files attached here.  Diff shows that **PlParam** values are empty in the lua version but are populated with the local host in the Perl version.
[olsrd-config-lua.txt](https://github.com/aredn/aredn/files/8225769/olsrd-config-lua.txt)
[olsrd-config-pl.txt](https://github.com/aredn/aredn/files/8225770/olsrd-config-pl.txt)

**Comment by aanon4** [comment]
@ab7pa thanks - can you try the new fix?

**Comment by ab7pa** [comment]
Yes, that fixed the issue.  Made the edit and restarted OLSR and everything came back up correctly.  Thanks very much!

**Comment by aanon4** [comment]
Excellent catch as always - much appreciated

**Comment by aanon4** [comment]
@dman776 @ae6xe I think this is good to go now

**Review by ae6xe — APPROVED** [review]
tested by @ab7pa .

**Pull request merged**
