### PR TITLE
Make index.html (which automatically redirects) respect dark mode

### PR DESCRIPTION
**Pull request by aanon4**

### CODE REVIEW

**Review by Orv — COMMENTED** [review]
Would prefer "AREDN Node" over "Mesh Node"

**Comment by aanon4** [comment]
That's what it's always said, but I can change it.

**Comment by aanon4** [comment]
https://github.com/aredn/aredn/pull/1472

**Comment by nc8q** [comment]
Would prefer "AREDN Node" over "Mesh Node"
+1 with Orv.

**Pull request merged**
